FROM golang:1.20

# Install libpcap development package
RUN apt-get update && apt-get install -y libpcap-dev

WORKDIR /app

# Copy and build the application
COPY . .
RUN go build -o kafka-sniffer ./cmd/sniffer

# This keeps the container running for debugging if needed
CMD ["tail", "-f", "/dev/null"]
